function main() {
  //
}

try {
  main();
} catch (err) {
  console.error("Error catched in main.js on calling main(). More info:");
  console.log(err);
}
